# Generated by Django 6.0 on 2026-01-03 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('number', models.CharField(max_length=20)),
                ('curso', models.TextField(blank=True)),
                ('etapa_funil', models.CharField(choices=[('novo', 'Novo'), ('negociacao', 'Negociação'), ('convertido', 'Convertido')], db_index=True, default='novo', max_length=15)),
            ],
        ),
    ]
